#!/usr/bin/env bash
set -euo pipefail

APP_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
ENV_FILE="$APP_ROOT/.env"

if [[ -f "$ENV_FILE" ]]; then
  echo "$ENV_FILE already exists; no values were changed."
  exit 0
fi

TAILSCALE_IP=""
if command -v tailscale >/dev/null 2>&1; then
  TAILSCALE_IP="$(tailscale ip -4 2>/dev/null | head -n 1 || true)"
fi
OBJECT_BIND_ADDRESS="127.0.0.1"
if [[ -n "$TAILSCALE_IP" ]]; then
  # Colima forwards VM ports through the host and cannot bind a Tailscale IP directly.
  OBJECT_BIND_ADDRESS="0.0.0.0"
fi
POSTGRES_PASSWORD="$(openssl rand -hex 24)"
S3_ACCESS_KEY="laiq_$(openssl rand -hex 10)"
S3_SECRET_KEY="$(openssl rand -hex 32)"

cat > "$ENV_FILE" <<ENV
REPORT_PLATFORM_POSTGRES_DB=laiq_report_platform
REPORT_PLATFORM_POSTGRES_USER=laiq_report_platform
REPORT_PLATFORM_POSTGRES_PASSWORD=$POSTGRES_PASSWORD
DATABASE_URL=postgresql://laiq_report_platform:$POSTGRES_PASSWORD@127.0.0.1:55432/laiq_report_platform
REPORT_PLATFORM_DB_SSL=disable
REPORT_PLATFORM_DB_POOL_MAX=20
REPORT_PLATFORM_DATABASE_BIND_ADDRESS=127.0.0.1

REPORT_PLATFORM_S3_BUCKET=laiq-report-platform
REPORT_PLATFORM_S3_ENDPOINT=http://$OBJECT_BIND_ADDRESS:59000
REPORT_PLATFORM_S3_REGION=us-east-1
REPORT_PLATFORM_S3_FORCE_PATH_STYLE=true
REPORT_PLATFORM_S3_ACCESS_KEY_ID=$S3_ACCESS_KEY
REPORT_PLATFORM_S3_SECRET_ACCESS_KEY=$S3_SECRET_KEY
REPORT_PLATFORM_S3_UPLOAD_URL_TTL_SECONDS=900
REPORT_PLATFORM_S3_READ_URL_TTL_SECONDS=300
REPORT_PLATFORM_OBJECT_BIND_ADDRESS=$OBJECT_BIND_ADDRESS

REPORT_PLATFORM_API_HOST=0.0.0.0
REPORT_PLATFORM_API_PORT=8788
REPORT_PLATFORM_MAX_JSON_BODY_BYTES=26214400
REPORT_PLATFORM_UPLOAD_SESSION_TTL_MS=86400000
REPORT_PLATFORM_UPLOAD_MAX_OBJECTS=250
REPORT_PLATFORM_UPLOAD_MAX_OBJECT_BYTES=262144000
REPORT_PLATFORM_UPLOAD_MAX_EXPORT_BYTES=2147483648

REPORT_PLATFORM_CODEX_MODEL=gpt-5.6-sol
REPORT_PLATFORM_CODEX_TIMEOUT_MS=120000
REPORT_PLATFORM_SESSION_TTL_MS=28800000
REPORT_PLATFORM_TRUST_PROXY=false
REPORT_PLATFORM_ENABLE_DEMO_DATA=false
REPORT_PLATFORM_ALLOW_LEGACY_SOURCE_IMPORTS=false
VITE_REPORT_ALLOW_FIXTURE_FALLBACK=false

REPORT_PLATFORM_BACKUP_RETENTION_DAYS=14
ENV

chmod 600 "$ENV_FILE"
echo "Created $ENV_FILE with machine-local credentials."
if [[ -n "$TAILSCALE_IP" ]]; then
  echo "Android/API host: http://$TAILSCALE_IP:8788"
  echo "Signed object uploads: http://$TAILSCALE_IP:59000"
else
  echo "Tailscale IP was not available; object storage is bound to loopback."
fi
